US8
Miladu93/meinMedikamentenTagebuch pull request #19
Opened 2023-08-01 14:36 UTC by Miladu93

this is the code for my US8

2023-08-02 08:03 UTC, Kheirah requested changes
Very good!

Have a look at the `index` below and see if you can add a unique key to your data if it doesn't exist yet, and then use that key for deletion.

2023-08-02 08:03 UTC, Kheirah commented on components/WeeklyOverview/index.js
> +              <SupplementWrapper key={index}>
Passing the `index` to the `key` prop **essentially is the same thing as not declaring a key at all.** It's the same mechanics under the hood because Next automatically applies the index to the key, **and that's not enough.** 😀 

Use an `id` or something else that is unique to your data.

2023-08-02 08:03 UTC, Kheirah commented on components/WeeklyOverview/index.js
> +    );
Using the `index` for deletion may cause unwanted side-effects. Use an `id` instead or something else unique to your data.

2023-08-02 08:03 UTC, Kheirah commented on components/WeeklyOverview/index.js
> +                  <DeleteButton onClick={() => handleDeleteMedication(weekday, index)}>
Instead of the `index`, pass the unique key to the `handleDeleteMedication`.

2023-08-03 08:32 UTC, Frank-Schaeske commented
Hi Milad, you have imported uid in your `WeeklyOverview` component, but it looks like you don’t use it for your `handleAddSupplement` function . I don’t really understand this, please check it again. Moreover, the naming with medication and supplement is quite confusing, you should choose one.

2023-08-03 09:47 UTC, Kheirah approved these changes
Well done, you may move on!
But have a look at the composite key again and see if you can use an id instead.

2023-08-03 09:47 UTC, Kheirah commented on components/WeeklyOverview/index.js
> +              <SupplementWrapper key={`${supplement.medicationName}-${supplement.dosage}`}>
This composite key might still not be unique when you enter the same med twice. For example, if I enter "Aspirin" and "100mg" twice, then this key is no longer unique.

2023-08-07 08:30 UTC, merged