userstory1
Miladu93/meinMedikamentenTagebuch pull request #6
Opened 2023-07-24 12:13 UTC by Miladu93

this is my user story 1

2023-07-24 14:34 UTC, AliaksandraNovikava requested changes
Hey @Miladu93 
Your first PR looks nice🚀

I left you some comments.
I'm a little confused why you already have a form when that is not part of your US😅

2023-07-24 14:34 UTC, AliaksandraNovikava commented on components/MediList/index.js
> +      id: dummyMedications.length + 1,
I would recommend to generate randomized ids using e.g. `uid`.

2023-07-24 14:34 UTC, AliaksandraNovikava commented on components/MediList/index.js
> +    console.log('Neues Medikament:', newMedikament);
You should remove all console.log before you make a PR 🤓

2023-07-24 14:34 UTC, AliaksandraNovikava commented on components/MediList/index.js
> +        />
I see no explicit form submission trigger. I would recommend to add a submit button within the form element.

2023-07-24 14:34 UTC, AliaksandraNovikava commented on components/MediList/index.js
> +`;
You should reduce this two styled components to one, because they have the same styling🎨

2023-07-24 14:34 UTC, AliaksandraNovikava commented on components/MediList/index.js
> +`;
You have two styled component with the same styling: `Container` and `MedikamentListContainer`. How about reducing them to one.

2023-07-25 08:24 UTC, Miladu93 commented
thanks Aliaksandra for your feedback! i just updated it, please check out

2023-07-25 08:49 UTC, Bilal4317 commented
nice you removed the console logs

2023-07-25 08:55 UTC, merged